### ISSUE TITLE
"The remote name could not be resolved: 'bccontainerhelper.azureedge.net'"

### ISSUE THREAD

**Issue by sergioramos83** [BusinessCentralApps/HelloWorld#3]
Hi!

We have an onprem server where we run the pipelines, and the scripts used are based on the ones provided here. Until yesterday everything was running fine, then suddenly they started giving the following error:

![image](https://github.com/BusinessCentralApps/Old.HelloWorld/assets/13440034/d42cac98-c331-45d6-affe-6d6f6f39c923)

The error looks to happen on this script:

![image](https://github.com/BusinessCentralApps/Old.HelloWorld/assets/13440034/d5e756d6-295e-4480-a4dc-b1fa309478e6)

Any idea why suddenly this error? Something have changed?

Thank you,

Sérgio

**Comment by UVARA** [comment]
@sergioramos83 Did you find a fix for this issue?

**Comment by sergioramos83** [comment]
> @sergioramos83 Did you find a fix for this issue?

Hi @UVARA!

Not really, what I did for the pipelines to keep running was to bypass the execution of this script... and I manually installed BcContainerHelper on the onprem server... Are you having the same issue?

**Comment by UVARA** [comment]
@sergioramos83 We changed the URL to $bcbaseurl = "https://bccontainerhelper.blob.core.windows.net/public", it looks like it is working with this example.

**Comment by sergioramos83** [comment]
> @sergioramos83 We changed the URL to $bcbaseurl = "https://bccontainerhelper.blob.core.windows.net/public", it looks like it is working with this example.

Hi @UVARA 

Thank you for the feedback.

I tested it right now and yes it's working fine... So apparently the other link suddenly went down... I'll close the issue as solved, thank you once again.
